# Generated by Django 5.1.2 on 2024-10-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('mileage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('salary', models.PositiveIntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
