# Generated by Django 5.1.2 on 2024-10-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_employee_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('run_time', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('director', models.CharField(max_length=200)),
            ],
        ),
    ]
